version: '3.9'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    env_file:
      - .env
    container_name: db
    volumes:
      - ./data:/var/lib/postgresql/data

  lang-trainer:
    build:
      context: .
      args:
        - REACT_APP_API_URI=http://localhost
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    container_name: lang-trainer

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: