name: CI on push

on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  server:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    services:
      postegres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: ginkgo -v ./app/...
        env:
          TEST_DB_STR=host: host=localhost port=5432 user=gotest password=tester dbname=testdb sslmode=disable
