name: CI on push

on:
  push:
    branches: [main]

jobs:
  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
    
    services:
      postegres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v ./app/...
        env:
          TEST_DB_STR: host=localhost port=5432 user=postgres password=postgres dbname=testdb sslmode=disable
